# Generated by Django 4.2.6 on 2023-10-30 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_add_flag_regex_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='catalog.classroom')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('classroom', 'student')},
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='enrollments.enrollment')),
                ('task', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='catalog.task')),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
