default:
  before_script:
    # check key to allow access
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "$TURTL_SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $TURTL_IP_ADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

variables:
  TURTL_DEPLOY_ADDRESS: "$TURTL_USER_NAME@$TURTL_IP_ADDRESS"

image: alpine:latest

stages: ["pull", "deploy"]

Get new files:
  stage: pull
  script:
    # Stop all processes
    - echo TODO stop server processes
    # Check out new changes from main branch
    - ssh $TURTL_DEPLOY_ADDRESS "cd $TURTL_SRC_PATH && git fetch --quiet && git checkout $CI_COMMIT_SHA"
  only:
    - main
  
Start backend:
  stage: deploy
  script:
    - cd $TURTL_SRC_PATH
    # Migrate new changes
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    # Restart backend
    - python3 manage.py runserver
  only:
    - main

Start frontend:
  stage: deploy
  script:
    - cd $TURTL_SRC_PATH_FRONTEND
    # Update contents and dependencies
    - npm install
    - npm run build
    # Restart frontend server
    - systemctl restart nginx
  only:
    - main
  needs: ["Start backend"]