default:
  before_script:
    # check key to allow access
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "$TURTL_SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $TURTL_IP_ADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

variables:
  TURTL_DEPLOY_ADDRESS: "$TURTL_USER_NAME@$TURTL_IP_ADDRESS"

image: alpine:latest

stages: ["pull", "deploy"]

Get new files:
  stage: pull
  script:
    # Stop all processes
    - ssh $TURTL_DEPLOY_ADDRESS "sudo systemctl stop backend-server.service"
    # Check out new changes from main branch
    - ssh $TURTL_DEPLOY_ADDRESS "cd $TURTL_SRC_PATH && git fetch --quiet && git checkout $CI_COMMIT_SHA"
  only:
    - main
  
Start backend:
  stage: deploy
  script:
    # Migrate new changes
    - ssh $TURTL_DEPLOY_ADDRESS "cd $TURTL_SRC_PATH && python3 manage.py makemigrations"
    - ssh $TURTL_DEPLOY_ADDRESS "cd $TURTL_SRC_PATH && python3 manage.py migrate"
    # Restart backend
    - ssh $TURTL_DEPLOY_ADDRESS "sudo systemctl start backend-server.service"
  only:
    - main
  needs: ["Get new files"]

Start frontend:
  stage: deploy
  script:
    # Update contents and dependencies
    - ssh $TURTL_DEPLOY_ADDRESS "cd $TURTL_SRC_PATH_FRONTEND && yarn install"
    - ssh $TURTL_DEPLOY_ADDRESS "cd $TURTL_SRC_PATH_FRONTEND && yarn run build"
    # Restart frontend server
    - ssh $TURTL_DEPLOY_ADDRESS "systemctl restart nginx &"
  only:
    - main
  needs: ["Start backend"]