# This docker-compose file can be used (run docker-compose up -d)
# to create a docker network (network1) with an isolated kali-container inside.
# This can be used to simulate a docker-service during development.
# The ID and status of the container can be found with the command: docker ps -a
version: "3"
services:
  kali-container:
    build:
      context: ./demo-virtualizations/kali-linux
      dockerfile: ./Dockerfile
    networks:
      task_network:
        ipv4_address: 192.168.254.2
      default:
  ubuntu-server:
    build:
      context: ./demo-virtualizations/ubuntu-nginx
      dockerfile: ./Dockerfile
    networks:
      task_network:
        ipv4_address: 192.168.254.3
      default:
  redis:
    image: 'redis:latest'

networks:
  task_network:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.254.0/24