# This docker-compose file can be used (run docker-compose up -d)
# to create a docker network (network1) with an isolated kali-container inside.
# This can be used to simulate a docker-service during development.
# The ID and status of the container can be found with the command: docker ps -a
version: "3"
services:

  app:
    image: kalilinux/kali-rolling
    networks:
      - network1
    command: tail -F /dev/null
  app2:
    image: praqma/network-multitool:latest
    networks:
      - network1
    command: tail -F /dev/null
  redis:
    image: 'redis:latest'

networks:
  network1:
    internal: true
