apiVersion: 1

datasources:
  - name: TURTL Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${GRAFANA_DB_USER}
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 18
    
