# Generated by Django 5.0 on 2025-07-11 12:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subnet', models.CharField(max_length=20)),
                ('vlan_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_id', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('cpu_cores', models.IntegerField(default=1)),
                ('memory_mb', models.IntegerField(default=512)),
                ('disk_gb', models.IntegerField(default=10)),
                ('purpose', models.CharField(choices=[('USER_SHELL', 'User Shell'), ('TASK_SUPPORT', 'Available inside a task as support')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subnet', models.CharField(max_length=20)),
                ('vlan_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='catalog.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='networks', to='vm_manager.networktemplate')),
            ],
        ),
        migrations.CreateModel(
            name='LabEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('cleanup', 'Cleanup')], default='provisioning', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_environments', to='catalog.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_environments', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_environments', to='vm_manager.network')),
            ],
            options={
                'unique_together': {('user', 'task')},
            },
        ),
        migrations.CreateModel(
            name='TaskVMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_internet_access', models.BooleanField(default=False)),
                ('max_runtime_hours', models.IntegerField(default=12)),
                ('auto_cleanup_after_hours', models.IntegerField(default=48)),
                ('network_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_configurations', to='vm_manager.networktemplate')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vm_configuration', to='catalog.task')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('creating', 'Creating'), ('error', 'Error')], default='creating', max_length=10)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('assigned_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='vm_manager.labenvironment')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms', to='vm_manager.network')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vm_manager.vmtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TaskVMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_ip_address', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.validate_ipv4_address])),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_templates', to='vm_manager.taskvmconfiguration')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm_manager.vmtemplate')),
            ],
        ),
    ]
