# Generated by Django 5.0 on 2025-07-14 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_virtualization'),
        ('vm_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='network',
            unique_together={('user', 'task')},
        ),
    ]
