# Generated by Django 5.0 on 2025-11-03 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0002_alter_network_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmtemplate',
            name='disk_gb',
        ),
        migrations.AlterField(
            model_name='labenvironment',
            name='network',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_environments', to='vm_manager.network'),
        ),
    ]
