# Generated by Django 5.0 on 2025-11-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0003_remove_vmtemplate_disk_gb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labenvironment',
            name='status',
            field=models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('stopped', 'Stopped'), ('cleanup', 'Cleanup')], default='provisioning', max_length=20),
        ),
    ]
