# Generated by Django 5.0 on 2025-11-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0005_alter_labenvironment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labenvironment',
            name='status',
            field=models.CharField(choices=[('provisioning', 'Provisioning'), ('starting', 'Starting'), ('active', 'Active'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('cleanup', 'Cleanup')], default='provisioning', max_length=20),
        ),
    ]
