# Generated by Django 5.0 on 2026-03-06 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0006_alter_labenvironment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labenvironment',
            name='last_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='labenvironment',
            name='stopped_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
