# Generated by Django 5.0 on 2026-03-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0007_labenvironment_last_seen_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskvmconfiguration',
            name='allow_internet_access',
        ),
        migrations.RemoveField(
            model_name='taskvmconfiguration',
            name='auto_cleanup_after_hours',
        ),
        migrations.RemoveField(
            model_name='taskvmconfiguration',
            name='max_runtime_hours',
        ),
    ]
