# Generated by Django 5.0 on 2026-04-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0008_remove_taskvmconfiguration_allow_internet_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labenvironment',
            name='status',
            field=models.CharField(choices=[('provisioning', 'Provisioning'), ('starting', 'Starting'), ('active', 'Active'), ('degraded', 'Degraded'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('cleanup', 'Cleanup')], default='provisioning', max_length=20),
        ),
    ]
