# Generated by Django 5.0 on 2026-04-11 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0009_alter_labenvironment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgePoolEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_name', models.CharField(max_length=20, unique=True)),
                ('allocated_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_pool_entry', to='vm_manager.network')),
            ],
            options={
                'ordering': ['bridge_name'],
            },
        ),
    ]
