# Generated by Django 5.0 on 2026-04-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0010_bridgepoolentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networktemplate',
            name='vlan_id',
        ),
    ]
