# Generated by Django 5.0 on 2026-04-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0011_remove_networktemplate_vlan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskvmtemplate',
            name='cloud_init',
            field=models.BooleanField(default=True),
        ),
    ]
