# Generated by Django 5.0 on 2026-04-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0012_taskvmtemplate_cloud_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labenvironment',
            name='network',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_environments', to='vm_manager.network'),
        ),
    ]
