# Generated by Django 5.0 on 2026-04-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0013_alter_labenvironment_network'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BridgePoolEntry',
        ),
    ]
