# Generated by Django 5.2.13 on 2026-04-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0013_alter_labenvironment_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
