# Generated by Django 3.0.7 on 2023-10-17 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20230918_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(editable=False, max_length=254, unique=True)),
                ('token', models.CharField(max_length=128)),
                ('expiration_date', models.DateTimeField()),
                ('target_role', models.CharField(choices=[('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Student')], default='STUDENT', max_length=10)),
                ('issuer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
