# Generated by Django 5.0 on 2025-07-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Virtualization',
        ),
    ]
