# Generated by Django 4.1.7 on 2023-05-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    operations = [
        migrations.CreateModel(
            name='HelpfulResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=48, null=True)),
                ('url', models.TextField()),
                ('classroom_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.classroomtemplate')),
            ],
        ),
    ]
