# Generated by Django 4.2.6 on 2023-10-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('pattern', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='acceptancecriteria',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='acceptancecriteria',
            name='regex',
        ),
        migrations.AlterField(
            model_name='acceptancecriteria',
            name='criteria_type',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('manual', 'Manual'), ('questionnaire', 'Questionnaire'), ('regex', 'Regex'), ('flag', 'Flag'), ('mixed', 'Mixed')], default='disabled', max_length=20),
        ),
        migrations.AlterField(
            model_name='acceptancecriteria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classroominstructor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='helpfulresource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='virtualization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='acceptancecriteria',
            name='flags',
            field=models.ManyToManyField(blank=True, to='catalog.flag'),
        ),
        migrations.AddField(
            model_name='acceptancecriteria',
            name='regexes',
            field=models.ManyToManyField(blank=True, to='catalog.regex'),
        ),
    ]
