# Generated by Django 4.1.7 on 2023-05-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_helpfulresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpfulresource',
            name='classroom_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_resources', to='catalog.classroomtemplate'),
        ),
    ]
