# Generated by Django 5.2.13 on 2026-04-29 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_virtualization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='instructors',
            field=models.ManyToManyField(related_name='classrooms', through='catalog.ClassroomInstructor', through_fields=('classroom', 'instructor'), to=settings.AUTH_USER_MODEL),
        ),
    ]
