# Generated by Django 4.2.6 on 2023-11-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_classroominstructor_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'classroom')},
        ),
    ]
