# Generated by Django 3.0.7 on 2023-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_alter_virtualenvironment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualenvironment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
